"""Changed token_data type in UserToken to str

Revision ID: ea00a02ff1a2
Revises: 34bf464cabf0
Create Date: 2025-07-28 15:12:42.440844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ea00a02ff1a2'
down_revision: Union[str, Sequence[str], None] = '34bf464cabf0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_token', 'token_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.String(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_token', 'token_data',
               existing_type=sa.String(),
               type_=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    # ### end Alembic commands ###
